name: Build unsigned IPA
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Generate Xcode Project
        run: xcodegen generate
      - name: Build IPA
        run: |
          xcodebuild clean build -project LogCam.xcodeproj -scheme LogCam -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath Build
          mkdir -p Payload
          mv Build/Build/Products/Release-iphoneos/LogCam.app Payload/
          zip -r LogCam.ipa Payload
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: LogCam.ipa
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
